#+TITLE: Scripts for Managing fMRI Data
#+AUTHOR: Caitlin Carey, Stephanie McMains, Alex Storer
#+EMAIL: smcmains@fas.harvard.edu
#+DATE: May, 2012
#+search org mode blah for help)

* Goals
This document describes the suite of scripts written to help you
run SPM batches created for a signle subject on all subjects.
Instead of the GIU, these scripts run via the command line and use bsub
to run all subjects quickly.

** Prerequisites
System requirements:
All scripts require that you be on the cluster, and were tested using
Matlab 2011b, spm version 8.4667, python 2.7.3.  (Use with older versions of matlab is unsupported, and is known
to fail using Matlab 2007). To access the scripts, you should be using the CBS defaut enviornment (http://cbs.fas.harvard.edu/science/core-facilities/neuroimaging/information-investigators/faq). To set your spm and matlab versions (which you will need to do), follow the appropriate FAQs.

Directory structure:
The scripts rely on the following directory structure which will automatically be created for you via the first script, getsubject.m.

#+begin_example
   |-mystudydir   
   |---120418_mysubject
   |-----RAW
   |-------/dicom files.../
   |-----analysis
   |-------paradigms
   |---------/run001,run002,.../
   |-------/spm files from first level analysis.../
   |-----batch
   |-------/spm batches.../
   |-----preproc
   |-------/converted dicoms, preprocessed data.../
   |-----output
   |-------/log_files with matlab output/	
#+end_example


** Summary

The following scripts have been written and should be included in your default path if you are using the
one listed on the FAQ site. 

| Script Name           | Details                                                     |
|-----------------------+-------------------------------------------------------------|
| ~getsubject.m~        | Pulls data using ~cbsget~ and creates a directory structure |
| ~genPreprocBatch.py~  | Generates preprocessing batches from template batch and executes batches |
| ~genL1Batches.py~     | Generates level 1 batches from template and executes them  |
| ~genArtBatches.m~     | Generates Art command and runs it  |
| ~genL1PostArt.m~      | Regenerates level 1 batches with art regressors and reruns level 1 analysis   |

* getsubject.m

~getsubject.m~ is a script that pulls data from the CBS
repository, converts it to SPM img format, and creates a directory structure for it that will allow the use
of the other scripts described here. 
~getsubject~ may be called from within Matlab or from the command line.  It takes
the following inputs:

~GETSUBJECT(subjectid, boldruns, structrun, fmruns, destpath)~
|-------------+-------------------------------------------------------------|
| Input       | Description                                                 |
|-------------+-------------------------------------------------------------|
| ~subjectid~ | the name of the subject, as as string  in quotes            |
|-------------+-------------------------------------------------------------|
| ~boldruns~  | a vector of the BOLD runs, seperated by a space             |
|-------------+-------------------------------------------------------------|
| ~structrun~ | a vector of the single struct-run                           |
|-------------+-------------------------------------------------------------|
| ~fmruns~    | a vector of the field-mapping runs. If no fieldmap, use []  |
|-------------+-------------------------------------------------------------|
| ~destpath~  | the full path to the location to place the output                |
|-------------+-------------------------------------------------------------|

For example:
#+begin_example
getsubject('120418_spmtest',[5],[4],[6 7],'/ncf/myspace/mystudydir')
#+end_example

This creates the following directory tree:
#+begin_example
   |-mystudydir   
   |---120418_spmtest
   |-----RAW
   |-----analysis
   |-------paradigms
   |-----batch
   |-----preproc
   |-----output
#+end_example

Within the RAW directory is a tarball (subjectname.tar.gz)
containing the DICOMs in a compressed format. 
The SPM converted data is in the preproc directory.

The files have also been renamed.  Because they are already in the
subject directory, they have been stripped of their subjectid, and are
renamed as follows:

|-------------------------+---------------------------------------------|
| File name               | Description                                 |
|-------------------------+---------------------------------------------|
| ~f-run001-006.img~      | Image 6 of the first BOLD run               |
|-------------------------+---------------------------------------------|
| ~s-struct.img~          | The structural image for the subject        |
|-------------------------+---------------------------------------------|
| ~s-fieldmap-mag-01.img~ | The magnitude of the fieldmap (if provided) |
|-------------------------+---------------------------------------------|
| ~s-fieldmap_phase.img~  | The phase of the fieldmap                   |
|-------------------------+---------------------------------------------|

Within the ~analysis~ directory is a ~paradigms~ directory, with a directory for each run.
For first level analysis, each condition should have it's own onset .txt file,
with each row being a single onset time.  The name of the file should be the name
given to each condition within the SPM batch, followed by the .txt extension.

* genPreprocBatch.py

Must use full pathnames

The goal of this script is to eliminate the need for the repeated use of the SPM GUI.
Using the GUI once, it is possible to create a template batch file, then use
this template file to generate the batch scripts for other subjects
with the same preprocessing steps.


~python genPreprocBatch.py -t TEMPLATE -p PATH -s SUBJECT1 SUBJECT2...~
or
~python genPreprocBatch.py -t TEMPLATE -p PATH -f SUBJECTFILE~
|---------------+-------------------------------------------------------------------------|
| Input         | Description                                                             |
|---------------+-------------------------------------------------------------------------|
| ~TEMPLATE~    |the full path and the name of the template batch created in the SPM GUI via a "save batch as script" command, that ends in _job.m |
|---------------+-------------------------------------------------------------------------|
| ~PATH~        | the path to the directory that contains all of your subjects            |
|---------------+-------------------------------------------------------------------------|
| ~SUBJECT1~    | a list separated by spaces containing your subjectids for analysis      |
|---------------+-------------------------------------------------------------------------|
| ~SUBJECTFILE~ | a file containing your subjectids, with each ID on its own line         |
|---------------+-------------------------------------------------------------------------|


For example:
#+begin_example
python genPreprocBatch.py -t /ncf/labspace/subject_dir/subject1/batch/preproc_job.m -p /ncf/labspace/subject_dir/ -s subject2 
#+end_example



genL1Batches -> can take one batch name, or many as a list
* Acknowledgments
These scripts were written by Alex Storer, Caitlin Carey and Stephanie
McMains with additional assistance from David Dodell-Feder.
